


// src/redux/constants.js
export const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE";
export const ADD_TASK = "ADD_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const UPDATE_TASK_STATUS = "UPDATE_TASK_STATUS";
export const SET_CHOSEN_DAY_TASKS = "SET_CHOSEN_DAY_TASKS";
export const SET_WEEKLY_TASKS = "SET_WEEKLY_TASKS";
export const SET_FILTERED_TASKS = "SET_FILTERED_TASKS";
